export const ManageUsersData = {
  title: "MANAGE USERS",
  inputLabel: "User Type",

  USERS_OBJ: {
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
    schoolAdmin: "School Administrator",
    districtAdmin: "District Administrator",
    admin: "Super Administrator",
    helpdesk: "Help Desk User",
  },
  users: [
    { lable: "Admin", value: "admin" },
    { lable: "Help Desk", value: "helpdesk" },
  ],
  helpDeskHeaders: ["Help Desk Name", "Help Desk Id", "Login Status"],
  adminTableHeaders: ["Administrator Name", "Administrator ID", "Login Status"],
  userDetails: [
    {
      id: 1,
      Id: "selectUser",
      placeholder: "Select",
      lable: "UserType",
      name: "user_type",
      type: "select",
      options: ["student", "teacher", "schoolAdmin", "districtAdmin", "parent"],
    },
    {
      id: 2,
      Id: "userSchools",
      placeholder: "Select",
      lable: "School",
      name: "schools",
      type: "select",
      options: [],
    },
    {
      id: 3,
      Id: "userLoginStatus",
      placeholder: "All",
      lable: "Login Status",
      name: "login_status",

      type: "select",
      options: [
        { lable: "All", value: "all" },
        { lable: "Active", value: "true" },
        { lable: "Inactive", value: "false" },
      ],
    },
    {
      id: 4,
      Id: "studentDateOfBirth",
      placeholder: "Select a date",
      lable: "Birth Date",
      name: "date_of_birth",
      type: "text",
    },
    {
      id: 5,
      Id: "userAssignmentStatus",
      placeholder: "All",
      lable: "Assignment Status",
      name: "assigned",
      type: "select",
      options: [
        { lable: "All", value: "all" },
        { lable: "Assigned", value: "true" },
        { lable: "Unassigned", value: "false" },
      ],
    },
    {
      id: 6,
      Id: "studentGrade",
      placeholder: "All",
      lable: "Grades",
      name: "grade",
      type: "select",
      options: [
        { lable: "Kindergarten", value: "K" },
        { lable: "First Grade", value: 1 },
        { lable: "Second Grade", value: 2 },
        { lable: "Third Grade", value: 3 },
        { lable: "Fourth Grade", value: 4 },
        { lable: "Fifth Grade", value: 5 },
        { lable: "Sixth Grade", value: 6 },
        { lable: "Seventh Grade", value: 7 },
        { lable: "Eighth Grade", value: 8 },
        { lable: "Ninth Grade", value: 9 },
        { lable: "Tenth Grade", value: 10 },
        { lable: "Eleventh Grade", value: 11 },
        { lable: "Twelth Grade", value: 12 },
        { lable: "Adult", value: "A" },
      ],
    },
  ],
  tableName: "STUDENT",
  searchPlaceholder: "Search by Alphabet, Names or User ID",
  actionPlaceholder: "Action",
  districtAdminActionOptions: [
    "Activate Login",
    "Deactivate Login",
    "Merge Users",
  ],
  districtAdminActionValues: ["activate", "deactivate", "merge"],

  actionOptions: [
    "Assign",
    "Unassign",
    "Activate Login",
    "Deactivate Login",
    "Merge User",
  ],
  actionValues: ["Assign", "Unassign", "activate", "deactivate", "merge"],

  teacherActionOptions: [
    "Assign",
    "Unassign",
    "Activate Login",
    "Deactivate Login",
  ],
  teacherActionValues: ["Assign", "Unassign", "activate", "deactivate"],
  exportUsers: "Export Users",
  fileName: "userData.csv",

  tableHeaders: [
    "Student Name",
    "Teacher Name",
    "School Administrator Name",
    "District Administrator Name",
  ],
  noUsers: " No Data Found",
};

export const changePassword = {
  title: "Change Password",
  passwordValidation1:
    "Password should contain 8 characters with one uppercase letter,one lowercase letter ,one number and one special character[!@#$%^&_*().-=+]",
  passwordValidation2:
    "Password should contain 8 characters with one uppercase letter,one lowercase letter ,one number and one special character [!@#$%^&_*().-=+]",
  changePasswordFields: [
    {
      id: "1",
      label: "",
      name: "password",
      placeholder: "Enter New Password",
    },
    {
      id: "2",
      label: "",
      name: "confirm_password",
      placeholder: "Confirm New Password",
    },
  ],
  positiveBtnText: "Save",
  negativeBtnText: "Cancel",
};
export const addUserData = {
  buttonsList: ["BASIC USER INFORMATION", "MANAGE USER'S ASSIGNMENTS"],
  studentInputFields: [
    {
      id: "1",
      Id: "studentId",
      lable: "Student ID*:",
      placeholder: "",
      name: "student_id",
      inputType: "text",
    },
    {
      id: "2",
      Id: "studentUserName",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },

    {
      id: "3",
      Id: "studentPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "studentRe-enterPassword",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },

    {
      id: "5",
      Id: "studentFirstName",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "studentLastName",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },

    {
      id: "7",
      Id: "studentMiddleInitial",
      lable: "Middle initial",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "8",
      Id: "studentNickName",
      lable: "Nick Name",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },

    {
      id: "9",
      Id: "studentDateOfBirth",
      lable: "Birthdate* (mm/dd/yyyy)",
      placeholder: "",
      name: "date_of_birth",
      inputType: "date",
    },

    {
      id: "10",
      Id: "studentGender",
      lable: "Sex Assigned At Birth",
      placeholder: "",
      name: "gender",
      inputType: "select",
      options: [
        { lable: "Male", value: "M" },
        { lable: "Female", value: "F" },
      ],
    },
    {
      id: "11",
      Id: "studentGrade",
      lable: "Grade*:",
      placeholder: "",
      name: "grade",
      inputType: "select",
      options: [
        { lable: "Kindergarten", value: "K" },
        { lable: "First Grade", value: 1 },
        { lable: "Second Grade", value: 2 },
        { lable: "Third Grade", value: 3 },
        { lable: "Fourth Grade", value: 4 },
        { lable: "Fifth Grade", value: 5 },
        { lable: "Sixth Grade", value: 6 },
        { lable: "Seventh Grade", value: 7 },
        { lable: "Eighth Grade", value: 8 },
        { lable: "Ninth Grade", value: 9 },
        { lable: "Tenth Grade", value: 10 },
        { lable: "Eleventh Grade", value: 11 },
        { lable: "Twelth Grade", value: 12 },
        { lable: "Adult", value: "A" },
      ],
    },

    {
      id: "12",
      Id: "studentRace",
      lable: "Race:",
      placeholder: "",
      name: "race",
      inputType: "multi-select",
      options: [
        { value: "White", label: "White" },
        {
          value: "Black or African American",
          label: "Black or African American",
        },
        {
          value: "American Indian or Alaska Native",
          label: "American Indian or Alaska Native",
        },
        { value: "Asian", label: "Asian" },
        {
          value: "Native Hawailian or Other Pacific",
          label: "Native Hawailian or Other Pacific",
        },
        { value: "Other", label: "Others" },
      ],
    },

    {
      id: "13",
      Id: "studentEthnicity",
      lable: "Ethnicity",
      placeholder: "",
      name: "ethnicity",
      inputType: "select",
      options: [
        { lable: "Hispanic or Latino", value: "Hispanic or Latino" },
        { lable: "Not Hispanic or Latino", value: "Not Hispanic or Latino" },
      ],
    },
    {
      id: "14",
      Id: "studentEmail",
      lable: "Student Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },

    {
      id: "15",
      Id: "parentEmail1",
      lable: "Parent Email Address 1:",
      placeholder: "",
      name: "parent_email_1",
      inputType: "text",
    },

    {
      id: "16",
      Id: "parentEmail2",
      lable: "Parent Email Address 2:",
      placeholder: "",
      name: "parent_email_2",
      inputType: "text",
    },

    {
      id: "17",
      Id: "studentPhone",
      lable: "Phone",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "18",
      Id: "studentState",
      lable: "State",
      placeholder: "",
      name: "state",
      inputType: "select",
    },
  ],
  printList: [
    {
      Id: "printBodyComposition",
      name: "print_body_composition",
      lable: "Print Body Composition",
    },
    {
      Id: "printReportsInSpanish",
      name: "print_reports_in_spanish",
      lable: "Print Reports in Spanish",
    },
    {
      Id: "permanentlyExempt",
      name: "permanently_exempt",
      lable: "Permanently Exempt",
    },
  ],

  teacherInputFields: [
    {
      id: "1",
      Id: "teacherId",
      lable: "Teacher ID*:",
      placeholder: "",
      name: "user_id",
      inputType: "text",
    },
    {
      id: "2",
      Id: "teacherUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "3",
      Id: "teacherPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "teacherRe-enterPassword",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "5",
      Id: "teacherFirstName",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "teacherLastName",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "7",
      Id: "teacherMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "8",
      Id: "studentNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },
    {
      id: "9",
      Id: "teacherEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "10",
      Id: "teacherEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "11",
      Id: "teacherEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "12",
      Id: "teacherPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "13",
      Id: "teacherState",
      lable: "State",
      placeholder: "",
      name: "state",
      inputType: "select",
    },
  ],

  schoolAdminInputFields: [
    {
      id: "1",
      Id: "schoolAdminEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "2",
      Id: "schoolAdminUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },

    {
      id: "3",
      Id: "schoolAdminPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "schoolAdminRe-enterPassword",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "5",
      Id: "schoolAdminFirstName",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "schoolAdminLastName",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "7",
      Id: "schoolAdminMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "8",
      Id: "schoolAdminNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },
    {
      id: "9",
      Id: "schoolAdminId",
      lable: "School Administrator ID*:",
      placeholder: "",
      name: "user_id",
      inputType: "text",
    },

    {
      id: "10",
      Id: "schoolAdminEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "11",
      Id: "schoolAdminEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "12",
      Id: "schoolAdminPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "13",
      Id: "schoolAdminState",
      lable: "State",
      placeholder: "",
      name: "state",
      inputType: "select",
    },
  ],

  districtAdminInputFields: [
    {
      id: "1",
      Id: "districtAdminEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
      isDisabled: false,
    },

    {
      id: "2",
      Id: "districtAdminUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "3",
      Id: "districtAdminPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
      isDisabled: false,
    },
    {
      id: "4",
      Id: "districtAdminRe-enterPassword",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "5",
      Id: "districtAdminFirstName",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "6",
      Id: "districtAdminLastName",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
      isDisabled: false,
    },

    {
      id: "7",
      Id: "districtAdminMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
      isDisabled: false,
    },

    {
      id: "8",
      Id: "districtAdminNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },

    {
      id: "9",
      Id: "districtAdminId",
      lable: "District Administrator ID*:",
      placeholder: "",
      name: "user_id",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "10",
      Id: "districtAdminSsoId",
      lable: "District SSO ID:",
      placeholder: "",
      name: "sso_id",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "11",
      Id: "districtAdminEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "12",
      Id: "districtAdminEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
      isDisabled: false,
    },

    {
      id: "13",
      Id: "districtAdminPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
      isDisabled: false,
    },
    {
      id: "14",
      Id: "districtAdminState",
      lable: "State",
      placeholder: "",
      name: "state",
      inputType: "select",
    },
    {
      id: "15",
      Id: "districtCode",
      lable: "4-Digit District Code:",
      name: "district_sso_id",
      inputType: "text",
      isDisabled: true,
    },
  ],
  DistrictAdminRolesList: [
    {
      Id: "schoolAdminRole",
      name: "school_admin_role",
      lable: "School Administrator",
    },

    {
      Id: "teacherRole",
      name: "teacher_role",
      lable: "Teacher",
    },
  ],

  superAdminInputFields: [
    {
      id: "1",
      Id: "superAdminUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "2",
      Id: "superAdminPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "3",
      Id: "superAdminRe-enterPassword",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "superAdminFirstname",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "5",
      Id: "superAdminLastname",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "superAdminMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "7",
      Id: "superAdminNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },

    {
      id: "8",
      Id: "superAdminEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "9",
      Id: "superAdminEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "10",
      Id: "superAdminEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "11",
      Id: "superAdminPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
  ],

  superAdminRolesList: [
    { name: "district_administrator_role", lable: "District Admin" },
    // { name: "state_administrator_role", lable: "State Admin" },
    { name: "teacher_role", lable: "Teacher" },
  ],

  stateAdminInputFields: [
    {
      id: "1",
      Id: "stateAdminId",
      lable: "State Administrator ID*:",
      placeholder: "",
      name: "user_id",
      inputType: "text",
    },
    {
      id: "2",
      Id: "stateAdminUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "3",
      Id: "stateAdminPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "stateAdminRe-enterPassword",
      lable: "Re-enter Password:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "5",
      Id: "stateAdminFirstName",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "stateAdminLastName",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "7",
      Id: "stateAdminMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "8",
      Id: "stateAdminNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },
    {
      id: "9",
      Id: "stateAdminEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "10",
      Id: "stateAdminEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "11",
      Id: "stateAdminEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "12",
      Id: "stateAdminPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
  ],
  stateAdminRolesList: [
    {
      name: "school_admin_role",
      lable: "School Administrator",
    },

    {
      name: "teacher_role",
      lable: "Teacher",
    },
  ],
  partnerInputFields: [
    {
      id: "1",
      Id: "partnerId",
      lable: "Partner ID*:",
      placeholder: "",
      name: "user_id",
      inputType: "text",
    },
    {
      id: "2",
      Id: "partnerUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "3",
      Id: "partnerPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "partnerRe-enterPassword",
      lable: "Re-enter Password:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "5",
      Id: "partnerFirstname",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "partnerLastname",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "7",
      Id: "partnerMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "8",
      Id: "partnerNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },

    {
      id: "8",
      Id: "partnerEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "9",
      Id: "partnerEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "10",
      Id: "partnerEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "11",
      Id: "partnerPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
  ],
  helpDeskInputFields: [
    {
      id: "1",
      Id: "helpDeskUsername",
      lable: "Username*:",
      placeholder: "",
      name: "user_name",
      inputType: "text",
    },
    {
      id: "2",
      Id: "helpDeskPassword",
      lable: "Password*:",
      placeholder: "",
      name: "password",
      inputType: "password",
    },
    {
      id: "3",
      Id: "helpDeskRe-enterPassword",
      lable: "Re-enter Password*:",
      placeholder: "",
      name: "re_enter_password",
      inputType: "password",
    },
    {
      id: "4",
      Id: "helpDeskFirstName",
      lable: "First Name*:",
      placeholder: "",
      name: "first_name",
      inputType: "text",
    },
    {
      id: "5",
      Id: "helpDeskLastName",
      lable: "Last Name*:",
      placeholder: "",
      name: "last_name",
      inputType: "text",
    },
    {
      id: "6",
      Id: "helpDeskMiddleInitial",
      lable: "Middle initial:",
      placeholder: "",
      name: "middle_initial",
      inputType: "text",
    },
    {
      id: "7",
      Id: "helpDeskNickName",
      lable: "Nickname",
      placeholder: "",
      name: "nick_name",
      inputType: "text",
    },

    {
      id: "8",
      Id: "helpDeskEmail",
      lable: "Email Address*:",
      placeholder: "",
      name: "email",
      inputType: "text",
    },
    {
      id: "9",
      Id: "helpDeskEmail1",
      lable: "Alternate Email Address 1:",
      placeholder: "",
      name: "email_1",
      inputType: "text",
    },
    {
      id: "10",
      Id: "helpDeskEmail2",
      lable: "Alternate Email Address 2:",
      placeholder: "",
      name: "email_2",
      inputType: "text",
    },

    {
      id: "11",
      Id: "helpDeskPhone",
      lable: "Phone:",
      placeholder: "",
      name: "phone",
      inputType: "text",
    },
    {
      id: "12",
      Id: "helpDeskState",
      lable: "State",
      placeholder: "",
      name: "state",
      inputType: "select",
    },
  ],
  helpDeskRolesList: [
    { name: "district_administrator_role", lable: "District Admin" },
    // { name: "state_administrator_role", lable: "State Admin" },
    { name: "teacher_role", lable: "Teacher" },
  ],

  rolesLabel: "Roles",

  login: [
    {
      Id1: "activeStatus",
      Id2: "InactiveStatus",
      label: "Login Status",
      name: "login_status",
      options: ["Active", "Inactive"],
    },
  ],
  positiveBtnText: "Next",
  positiveBtnText2: "Save",
  negativeBtnText: "Cancel",
};

export const userAssignmentData = {
  title: "Add School/Class",
  schoolAdminTitle: "Add Schools",
  schoolAdminModalName1: "Add School/Class",
  schoolAdminModalName2: "Add School",
  positiveBtnText: "Add",
  positiveBtnText2: "Unassign",
  negativeBtnText: "Cancel",
  negativeBtnText2: "No",
  classUnAssign: "Unassign from School?",
  unAssignTitle: "Unassign from Class ?",
  schoolDesc: ` Selecting "Unassign" will remove this user's association with this school (including classes). Are you sure you want to continue`,
  unAssigndesc: `Selecting "Unassign" will remove this user's association with this class. `,
  unAssignText1: "This User will be unassigned from ",
  unAssignText2: "And any current-year classes in this school",
};

export const manageUsersTableData = {
  tableHeaders: {
    student: "Student Name",
    teacher: "Teacher Name",
    schoolAdmin: "School Administrator Name",
    districtAdmin: "District Administrator Name",
  },

  student: {
    student_id: "Student ID",
    date_of_birth: "Birth Date",
    grade: "Grade",
    gender: "Sex Assigned At Birth",
    login_status: "Login Status",
    assignedToClass: "Assigned to Class",
  },

  teacher: {
    user_id: "Teacher ID",
    login_status: "Login Status",
    assignedToClass: "Assigned to Class",
  },

  schoolAdmin: {
    user_id: "School Administrator ID ",
    login_status: "Login Status",
    admin_assigned_to_school: "Assigned to School",
  },

  districtAdmin: {
    user_id: "District Administrator ID",
    login_status: "Login Status",
  },
};
